### ISSUE TITLE
Unescaped spaces in IRIs

### ISSUE THREAD

**Issue by wouterbeek** [nheist/CaLiGraph#1]
Thank you for this great resource!

There is a minor issue with unescaped spaces appearing in an IRI in file `caligraph-ontology.nt.bz2` line 2.405.570:

```
<http://caligraph.org/ontology/RestrictionHasValue_location_Allentown,_Pennsylvania> <http://www.w3.org/2000/01/rdf-schema#label> <Restriction onProperty=location hasValue=Allentown,_Pennsylvania> .
```

**Comment by nheist** [comment]
Hi Wouter,
thank you for the feedback! It seems like the object of the label is currently encoded as an IRI but should actually be a string. I can fix that very easily, but I am currently on vacation. So it might take until 19th of November until I can upload an updated version. A quick fix for now would be to exclude all lines with rdfs:label in that file. I will inform you as soon as I’m able to deploy the fix.
Thanks again and best regards,
Nico

**Comment by nheist** [comment]
Hi Wouter,
I just found the time to upload a fixed version of the dataset on Zenodo. The links on the CaLiGraph website are now up to date as well.
Best, Nico

**Comment by wouterbeek** [comment]
@nheist I have re-downloaded the ontology file from http://caligraph.org/resources.html (the download link is https://zenodo.org/record/3531971/files/caligraph-ontology.nt.bz2?download=1).  That file still has the same issue.  Maybe I'm downloading from the wrong location / download link?

**Comment by nheist** [comment]
@wouterbeek The download link is correct. I have just downloaded the file and double-checked that the labels are encoded as strings. Do you get the exact same error as before? And is the md5sum of your file cd34a2e485eba107d89aef34c32c44c1 ?

**Comment by wouterbeek** [comment]
Hmm, something does not seem right here.  I'm sharing the exact commands this I use:

```
$ wget https://zenodo.org/record/3531971/files/caligraph-ontology.nt.bz2?download=1
$ md5sum caligraph-ontology.nt.bz2\?download\=1 
$ bunzip2 caligraph-ontology.nt.bz2\?download\=1 
bunzip2: Can't guess original name for caligraph-ontology.nt.bz2?download=1 -- using caligraph-ontology.nt.bz2?download=1.out
$ serdi caligraph-ontology.nt.bz2\?download\=1.out > /dev/null 
error: caligraph-ontology.nt.bz2?download=1.out:2409254:70: invalid IRI character ` ' (escape %20)
error: caligraph-ontology.nt.bz2?download=1.out:2409254:70: bad subject
```

^ In the last step I use Serdi, the command-line utility that comes with Serd (https://github.com/drobilla/serd).  Any other standards-compliant N-Triples parser will do.

Can you share your sequence of commands / do you see the same thing?

**Comment by nheist** [comment]
@wouterbeek You're right, there is still an issue in the file. Unfortunately I can't test the new version thoroughly right now as I'm not back in the office yet. I will be able to do that during the next week and I'll notify you as soon as I'm done. Sorry for the inconveniences!

**Comment by wouterbeek** [comment]
No problem, we'll pick this up later.

**Comment by nheist** [comment]
Hi @wouterbeek,
I was finally able to upload a new version of the data set on Zenodo (they had a few technical problems).
The download links on the caligraph.org website are also up to date. I tested your setup with serdi and didn't run into any problems. Let me know if there is anything else that I can help you with!
Best, Nico
