### ISSUE TITLE
problems about tuning entity disambiguation parameters

### ISSUE THREAD

**Issue by ylenchen** [nheist/CaLiGraph#10]
Hi, your work is very intersting, but I meet some problems when reproduce the result.

I input
```python tune_entity_dismabiguation.py```

but I'm required to add some parameters
```
usage: tune_entity_disambiguation.py [-h] [--approach APPROACH] [--corpus {LIST,NILK}] [-ss {5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100}]
                                     [--mm_approach MM_APPROACH] [--me_approach ME_APPROACH] [--mm_threshold MM_THRESHOLD] [--me_threshold ME_THRESHOLD]
                                     [--path_threshold PATH_THRESHOLD] [--me_cluster_threshold ME_CLUSTER_THRESHOLD] [--cpus CPUS]
                                     config_file
tune_entity_disambiguation.py: error: the following arguments are required: config_file
```
Could you please give me the full instruction or give me the parameters required?

Thanks a lot!

**Comment by nheist** [comment]
Hi,
unfortunately I can't provide you any specific parameter configuration as this completely depends on what you are trying to achieve. You can trigger the help command (`-h`) for further descriptions of the parameters and have a look at the actual script and the paper describing NASTyLinker [1] if you want to rerun any specific experiments.
Best,
Nico

[1] https://arxiv.org/pdf/2303.04426
