### ISSUE TITLE
Many peoples in clgo:Organization 

### ISSUE THREAD

**Issue by Benja1972** [nheist/CaLiGraph#11]
Hi team,
Thank you for nice work on semantic typing of concepts from wikipedia. I was struggling with same task for specific problem in my team.

I have one question:
What is the source of kind on inconsistency in sense that in class  clgo:Organization there are many peoples?

Thank you 
Sergei

**Comment by nheist** [comment]
Hi Sergei,

thanks for making us aware of this issue. One possible reason is that several people also have a "one-man business" named after them. The extraction pipeline merges these occurrences as they refer more or less to the same entity.
However, we have implemented some changes that may mitigate the impact of such constellations. We are currently testing it - I'll let you know as soon as it's production-ready.

Best
Nico

**Comment by Benja1972** [comment]
Thank you Nico for prompt reply! I will wait for latest updates fro you

Best,
Sergei
