### ISSUE TITLE
Blank spaces in IRIs in caligraph-ontology.nt

### ISSUE THREAD

**Issue by kathrinrin** [nheist/CaLiGraph#12]
We would love to use the CaLiGraph data for research purposes over here in Amsterdam (VU / Triply), but unfortunately bumped into reusability issues due to invalid IRIs that contain blank spaces. 

We don't have a complete overview, but we did look extensively into `caligraph-ontology.nt` downloaded and extracted from [here](https://zenodo.org/record/7962777/files/caligraph-ontology.nt.bz2?download=1). 

`riot --validate caligraph-ontology.nt` results in: 
`ERROR riot            :: [line: 4510843, col: 77] Bad character in IRI (space): <http://caligraph.org/ontology/RestrictionHasValue_birthPlace_Trentino-Alto[space]...>`

The complete subject of the triple in this line is: 
`<http://caligraph.org/ontology/RestrictionHasValue_birthPlace_Trentino-Alto Adige/S%C3%BCdtirol>.`

Blank spaces in IRIs seem to be the only issue in this file.

**Comment by kathrinrin** [comment]
Hi Nico, 

Wow, thank you for the fast response! 

I already fixed the file with this command: `perl -pe 's/(<[^<>]*) /$1=~s| |%20|gr/ge' caligraph-ontology.nt > caligraph-ontology-cleaned.nt`. 

Best, 
Kathrin

**Comment by nheist** [comment]
Hi Hathrin,

thanks again for letting me know about this issue. It is fixed in the new version 3.1.1 of CaLiGraph.

All the best,
Nico

**Comment by kathrinrin** [comment]
Wow great, thank you so much, Nico!
